name = "cloudflare-workers-esbuild-template"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"